import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from '@/shared/ui/Button';
import { useOrders } from '@/entities/order/api';
import { OrderStatus } from '@/entities/order/types';
import { formatPrice, formatDate } from '@/shared/utils/formatters';
import { useAuthStore } from '@/features/auth';
export const CustomerDashboard = () => {
    const { user } = useAuthStore();
    const { data: orders } = useOrders(user?.id);
    return (_jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8", children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 mb-8", children: "My Account" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-8", children: [_jsxs("div", { className: "bg-white p-6 rounded-lg shadow-md", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: "Total Orders" }), _jsx("p", { className: "text-3xl font-bold text-primary-600", children: orders?.length || 0 })] }), _jsxs("div", { className: "bg-white p-6 rounded-lg shadow-md", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: "Pending Orders" }), _jsx("p", { className: "text-3xl font-bold text-yellow-600", children: orders?.filter(order => order.status === OrderStatus.PENDING).length || 0 })] }), _jsxs("div", { className: "bg-white p-6 rounded-lg shadow-md", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: "Completed Orders" }), _jsx("p", { className: "text-3xl font-bold text-green-600", children: orders?.filter(order => order.status === OrderStatus.COMPLETED).length || 0 })] })] }), _jsxs("div", { className: "bg-white shadow-md rounded-lg overflow-hidden", children: [_jsx("div", { className: "px-6 py-4 border-b border-gray-200", children: _jsx("h2", { className: "text-lg font-medium text-gray-900", children: "Order History" }) }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-full divide-y divide-gray-200", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Order ID" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Date" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Total" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Status" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Actions" })] }) }), _jsx("tbody", { className: "bg-white divide-y divide-gray-200", children: orders?.map((order) => (_jsxs("tr", { children: [_jsxs("td", { className: "px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900", children: ["#", order.id] }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-gray-500", children: formatDate(order.createdAt) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-gray-900", children: formatPrice(order.totalPrice) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsx("span", { className: `px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${order.status === OrderStatus.COMPLETED
                                                        ? 'bg-green-100 text-green-800'
                                                        : order.status === OrderStatus.PENDING
                                                            ? 'bg-yellow-100 text-yellow-800'
                                                            : 'bg-gray-100 text-gray-800'}`, children: order.status }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm font-medium", children: _jsx(Button, { variant: "outline", size: "sm", children: "View Details" }) })] }, order.id))) })] }) })] })] }));
};
//# sourceMappingURL=index.js.map