import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuthStore } from '@/features/auth/model/authStore';
import { useCartStore } from '@/features/cart/model/cartStore';
import { Button } from '@/shared/ui/Button';
import { ShoppingCartIcon, UserIcon, Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline';
export const Navbar = () => {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    const { user, isAuthenticated, logout } = useAuthStore();
    const { items } = useCartStore();
    const navigate = useNavigate();
    const cartItemsCount = items.reduce((total, item) => total + item.quantity, 0);
    const handleLogout = () => {
        logout();
        navigate('/');
    };
    return (_jsxs("nav", { className: "bg-white shadow-lg sticky top-0 z-50", children: [_jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between h-16", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Link, { to: "/", className: "flex-shrink-0 font-bold text-xl text-primary-600", children: "EcommerceApp" }), _jsxs("div", { className: "hidden md:ml-6 md:flex md:space-x-8", children: [_jsx(Link, { to: "/", className: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium", children: "Home" }), _jsx(Link, { to: "/categories", className: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium", children: "All Categories" }), _jsx(Link, { to: "/products?category=men", className: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium", children: "Men" }), _jsx(Link, { to: "/products?category=women", className: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium", children: "Women" }), _jsx(Link, { to: "/products?category=kids", className: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium", children: "Kids" })] })] }), _jsxs("div", { className: "flex items-center", children: [_jsxs("div", { className: "hidden md:ml-4 md:flex md:items-center space-x-4", children: [_jsxs(Link, { to: "/cart", className: "relative p-2 text-gray-400 hover:text-gray-500", children: [_jsx(ShoppingCartIcon, { className: "h-6 w-6" }), cartItemsCount > 0 && (_jsx("span", { className: "absolute -top-1 -right-1 bg-primary-600 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center", children: cartItemsCount }))] }), isAuthenticated ? (_jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs(Link, { to: user?.role === 'admin'
                                                        ? '/admin'
                                                        : user?.role === 'staff'
                                                            ? '/staff'
                                                            : '/customer', className: "flex items-center text-gray-500 hover:text-gray-700", children: [_jsx(UserIcon, { className: "h-5 w-5 mr-1" }), user?.name] }), _jsx(Button, { variant: "outline", size: "sm", onClick: handleLogout, children: "Logout" })] })) : (_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Link, { to: "/login", children: _jsx(Button, { variant: "outline", size: "sm", children: "Login" }) }), _jsx(Link, { to: "/register", children: _jsx(Button, { size: "sm", children: "Register" }) })] }))] }), _jsxs("div", { className: "md:hidden flex items-center", children: [_jsxs(Link, { to: "/cart", className: "relative p-2 text-gray-400 hover:text-gray-500 mr-2", children: [_jsx(ShoppingCartIcon, { className: "h-6 w-6" }), cartItemsCount > 0 && (_jsx("span", { className: "absolute -top-1 -right-1 bg-primary-600 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center", children: cartItemsCount }))] }), _jsx("button", { onClick: () => setIsMenuOpen(!isMenuOpen), className: "inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-primary-500", children: isMenuOpen ? (_jsx(XMarkIcon, { className: "block h-6 w-6" })) : (_jsx(Bars3Icon, { className: "block h-6 w-6" })) })] })] })] }) }), isMenuOpen && (_jsx("div", { className: "md:hidden", children: _jsxs("div", { className: "pt-2 pb-3 space-y-1", children: [_jsx(Link, { to: "/", className: "block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800", children: "Home" }), _jsx(Link, { to: "/categories", className: "block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800", children: "All Categories" }), _jsx(Link, { to: "/products?category=men", className: "block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800", children: "Men" }), _jsx(Link, { to: "/products?category=women", className: "block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800", children: "Women" }), _jsx(Link, { to: "/products?category=kids", className: "block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800", children: "Kids" }), isAuthenticated ? (_jsxs(_Fragment, { children: [_jsx(Link, { to: user?.role === 'admin'
                                        ? '/admin'
                                        : user?.role === 'staff'
                                            ? '/staff'
                                            : '/customer', className: "block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800", children: "Dashboard" }), _jsx("button", { onClick: handleLogout, className: "block w-full text-left pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800", children: "Logout" })] })) : (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/login", className: "block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800", children: "Login" }), _jsx(Link, { to: "/register", className: "block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800", children: "Register" })] }))] }) }))] }));
};
//# sourceMappingURL=index.js.map