import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCartStore } from '@/features/cart';
import { CartItem, CartSummary } from '@/features/cart';
import { formatPrice } from '@/shared/utils/formatters';
export const ReviewStep = () => {
    const { items, getTotalPrice } = useCartStore();
    const totalPrice = getTotalPrice();
    return (_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-medium text-gray-900 mb-6", children: "Review Your Order" }), _jsx("div", { className: "border-b border-gray-200 pb-4 mb-4", children: _jsx("h3", { className: "text-md font-medium text-gray-900", children: "Order Items" }) }), _jsx("div", { className: "space-y-4 mb-6", children: items.map((item) => (_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center", children: [_jsx("img", { src: item.product.image || 'https://via.placeholder.com/60', alt: item.product.name, className: "w-16 h-16 object-cover rounded-md mr-4" }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-gray-900", children: item.product.name }), _jsxs("p", { className: "text-gray-600", children: ["Quantity: ", item.quantity] })] })] }), _jsx("p", { className: "font-medium text-gray-900", children: formatPrice(item.product.price * item.quantity) })] }, item.product.id))) }), _jsxs("div", { className: "border-t border-gray-200 pt-4", children: [_jsxs("div", { className: "flex justify-between text-sm text-gray-600 mb-1", children: [_jsx("span", { children: "Subtotal" }), _jsx("span", { children: formatPrice(totalPrice) })] }), _jsxs("div", { className: "flex justify-between text-sm text-gray-600 mb-1", children: [_jsx("span", { children: "Tax" }), _jsx("span", { children: formatPrice(totalPrice * 0.1) })] }), _jsxs("div", { className: "flex justify-between text-sm text-gray-600 mb-1", children: [_jsx("span", { children: "Shipping" }), _jsx("span", { className: "text-green-600", children: "Free" })] }), _jsxs("div", { className: "flex justify-between text-lg font-semibold text-gray-900 mt-2", children: [_jsx("span", { children: "Total" }), _jsx("span", { children: formatPrice(totalPrice * 1.1) })] })] })] }));
};
//# sourceMappingURL=ReviewStep.js.map